import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    '*.{js,ts,jsx,tsx,mdx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        isabelline: {
          DEFAULT: '#f3ecd8',
          100: '#27200c',
          200: '#4e4018',
          300: '#755f24',
          400: '#9c7f30',
          500: '#c39f3c',
          600: '#cfb263',
          700: '#dbc58a',
          800: '#e7d9b1',
          900: '#f3ecd8',
        },
        'soft-fawn': {
          50: '#f9f5eb',
          100: '#f3ecd8',
          200: '#e7d9b1',
          300: '#dbc58a',
          400: '#cfb263',
          500: '#c39f3c',
          600: '#9c7f30',
          700: '#755f24',
          800: '#4e4018',
          900: '#27200c',
          950: '#1b1608',
        },
        timberwolf: {
          DEFAULT: '#d6ccc2',
          100: '#312921',
          200: '#625241',
          300: '#937a62',
          400: '#b6a391',
          500: '#d6ccc2',
          600: '#ded6ce',
          700: '#e7e0da',
          800: '#efebe7',
          900: '#f7f5f3',
        },
        linen: {
          DEFAULT: '#f5ebe0',
          100: '#473017',
          200: '#8e5f2e',
          300: '#c78f52',
          400: '#debd99',
          500: '#f5ebe0',
          600: '#f7efe6',
          700: '#f9f3ed',
          800: '#fbf7f3',
          900: '#fdfbf9',
        },
        champagne_pink: {
          DEFAULT: '#e3d5ca',
          100: '#38291e',
          200: '#70523b',
          300: '#a87b59',
          400: '#c5a891',
          500: '#e3d5ca',
          600: '#e8ddd4',
          700: '#eee6df',
          800: '#f4eeea',
          900: '#f9f7f4',
        },
        pale_dogwood: {
          DEFAULT: '#d5bdaf',
          100: '#33241b',
          200: '#664735',
          300: '#986b50',
          400: '#ba937c',
          500: '#d5bdaf',
          600: '#ddcabf',
          700: '#e6d7cf',
          800: '#eee4df',
          900: '#f7f2ef',
        },
      },
      fontFamily: {
        serif: ['var(--font-playfair)', 'Playfair Display', 'serif'],
        sans: ['var(--font-source-sans)', 'Source Sans 3', 'sans-serif'],
        script: ['var(--font-dancing-script)', 'Dancing Script', 'cursive'],
        'bodoni-moda': ['var(--font-bodoni-moda)', 'Bodoni Moda', 'serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
